name: Deploy

env:
  DOCS_BASE_URL: https://chunithmsg.github.io/chuni-tools/

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

concurrency:
  group: ${{ github.workflow }}__${{ github.ref }}
  cancel-in-progress: true

jobs:
  # lint:
  #   name: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: setup nodejs, pnpm and installs packages
  #       uses: ./.github/actions/setup

  #     - run: pnpm run lint

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs, pnpm and installs packages
        uses: ./.github/actions/setup

      - run: pnpm run build:apps

      - name: saves build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: /apps/docs/dist

  # test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: setup nodejs, pnpm and installs packages
  #       uses: ./.github/actions/setup

  #     - run: pnpm run test

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: deploy
        run: echo "Deploying to production"
